[wip]feature/kubernetes pod spec configure
treasure-data/digdag pull request #1265
Opened 2019-11-23 06:58 UTC by TrsNium

2019-11-28 06:00 UTC, TrsNium commented on digdag-standards/src/main/java/io/digdag/standards/command/kubernetes/DefaultKubernetesClient.java
> +    protected JsonNode convertConfigToJsonNode(final Config config, String key) {
@muga 
I have a question about this method.
This method purpose is same to bellow method.
https://github.com/treasure-data/digdag/blob/a7039bc76c3de08022411b8897517757bec42172/digdag-client/src/main/java/io/digdag/client/config/Config.java#L385
So I' like to make `Config.tryParse Nested` method to public if you allow that.

2019-12-04 04:42 UTC, TrsNium commented
@muga  @yoyama 
Could you review this PR?

2019-12-09 07:08 UTC, sonots commented on digdag-standards/src/main/java/io/digdag/standards/command/kubernetes/DefaultKubernetesClient.java
> +          if (kubernetesNode.has("pod")) {
How about `spec` rather than `pod` as I commented?

2019-12-09 07:08 UTC, sonots commented on digdag-standards/src/main/java/io/digdag/standards/command/kubernetes/DefaultKubernetesClient.java
> +      }
fix indent

2019-12-09 07:09 UTC, sonots commented on digdag-standards/src/main/java/io/digdag/standards/command/kubernetes/DefaultKubernetesClient.java
> +      return podSpecBuilder.build();
fix indent

2019-12-17 04:43 UTC, muga commented
@TrsNium Thank you for making the change for that. It's good. I started taking a look. But if you have a time, please make the specification of the options that you're introducing in the description of this PR.

2020-01-31 00:06 UTC, TrsNium commented
@muga @frsyuki 
we should consider to support resources other than pod (such as PersistentVolumeClaim, PersistentVolume, and ConfigMap)

2020-12-11 04:24 UTC, yoyama requested changes
Could you rebase to the latest v0_10 branch.
We changed CI service from TravisCI to GitHub Action.

2020-12-22 07:19 UTC, yoyama commented
@TrsNium I would like to close this PR because we stop working on `v0_10` branch.
The `v0_10` branch has been merged to `master`.
So please reopen a PR on `master` branch if need.

2020-12-22 07:19 UTC, closed without merging