Add ssl option to RemoteDatabaseConfig
treasure-data/digdag pull request #1690
Opened 2022-01-14 07:02 UTC by gumigumi4f

We are trying to connect background postgresql database with server and client certificates. (Ex: Google Cloud SQL)
But there is no option to change sslfactory and sslmode and we cannot connect database.

After merging this PR, we are able to connect postgresql with certificates by adding the following settings and placing the certificates to `${user.home}/.postgresql/`.
```
database.ssl = true
database.sslfactory = org.postgresql.ssl.LibPQFactory
database.sslmode = verify-ca
```

2022-04-15 01:18 UTC, yoyama commented
@gumigumi4f Thank you for your contribution.
I think we should update the document for new configuration.
https://docs.digdag.io/command_reference.html#server
You can update the doc in `digdag-docs` directory.

2022-04-18 07:29 UTC, yoyama requested changes
As comment, please update document.

2022-05-19 08:37 UTC, gumigumi4f commented
Sorry for late response.
I have added new option such as sslcert and updated digdag-docs.

2022-07-05 02:40 UTC, yoyama commented on digdag-docs/src/command_reference.rst
> +* database.sslmode (string)
Could you describe what string are accepted for this option ?

2022-07-05 02:41 UTC, yoyama commented on digdag-docs/src/command_reference.rst
> +* database.sslcert (string)
Is this a path to cert file ?

2022-07-05 02:41 UTC, yoyama commented on digdag-docs/src/command_reference.rst
> +* database.sslrootcert (string)
ditto

2022-07-22 08:19 UTC, gumigumi4f commented
I have updated the docs

2022-07-28 09:43 UTC, yoyama commented
Thank you for your contribution. After CI has passed, I will approve it.

2022-07-29 01:42 UTC, yoyama approved these changes
LGTM 👍 
Thank you for your contribution

2022-07-29 01:43 UTC, merged